import { HomeContent } from "./homeTypes";

export const homeContent: HomeContent = {
  techTags: ["React", "Next.js", "Go", "PostgreSQL", "Docker", "TypeScript", "Node.js"],
  heroPreviewCards: [
    {
      title: "Booking Systems",
      detail: "Scheduling and RBAC",
      serial: "01",
      stack: ["Node.js", "PostgreSQL", "JWT"],
      palette: {
        glow: "#ff8a5b",
        edge: "#ff6f54",
        wash: "rgba(255,111,84,0.22)",
        ink: "#ffd6c8",
      },
      featured: false,
    },
    {
      title: "Performance Optimization",
      detail: "40-60% speed gains",
      serial: "02",
      stack: ["Next.js SSR", "Code Split", "Caching"],
      palette: {
        glow: "#ffb347",
        edge: "#ff8a3d",
        wash: "rgba(255,179,71,0.2)",
        ink: "#fff1c9",
      },
      featured: true,
    },
    {
      title: "CI/CD Infrastructure",
      detail: "Zero-downtime deploy",
      serial: "03",
      stack: ["GitHub Actions", "Docker", "AWS"],
      palette: {
        glow: "#28d7e5",
        edge: "#1dbfb0",
        wash: "rgba(40,215,229,0.18)",
        ink: "#d6fbff",
      },
      featured: false,
    },
    {
      title: "Microservices API",
      detail: "Scalable architecture",
      serial: "04",
      stack: ["Go Gin", "REST", "Webhooks"],
      palette: {
        glow: "#b083ff",
        edge: "#8f6cff",
        wash: "rgba(176,131,255,0.18)",
        ink: "#efe4ff",
      },
      featured: false,
    },
    {
      title: "Full-Stack Platforms",
      detail: "15+ production features",
      serial: "05",
      stack: ["React", "Node.js", "PostgreSQL"],
      palette: {
        glow: "#ff6fa3",
        edge: "#ff5c88",
        wash: "rgba(255,111,163,0.18)",
        ink: "#ffd9e8",
      },
      featured: false,
    },
  ],
  featuredProjects: [
    {
      title: "Performance Optimization Suite",
      tag: "Full-Stack",
      description: "Achieved 40-60% speed gains through Next.js SSR, code splitting, and advanced caching on production platforms serving 50-80+ daily users.",
      year: "2026",
      stack: ["Next.js", "React", "Tailwind CSS", "Performance Tuning"],
      image: "/reference/dragon-bodies1.png",
    },
    {
      title: "Booking & Session Platform",
      tag: "Full-Stack",
      description:
        "Built backend infrastructure with scheduling workflows, role-based access control, and transactional data flows for enterprise-grade bookings.",
      year: "2026",
      stack: ["Node.js", "PostgreSQL", "JWT Auth", "REST APIs"],
      image: "/reference/0d770529-22f8-486b-b77f-b4c3985a32f3.png",
    },
    {
      title: "CI/CD & DevOps Infrastructure",
      tag: "DevOps",
      description:
        "Designed GitHub Actions pipelines and Docker configurations enabling zero-downtime deployments on AWS and Vercel with 99.9% uptime.",
      year: "2026",
      stack: ["GitHub Actions", "Docker", "AWS", "Vercel"],
      image: "/reference/3a26bd8d-1922-4717-975d-a8861e6ba75c.png",
    },
  ],
  processSteps: [
    "Understand problem & system requirements",
    "Design architecture & database schema",
    "Build frontend & backend in parallel",
    "Optimize performance & deploy to production",
  ],
  bountyPosters: [
    { id: "bp-1", label: "Board", value: "Wanted Index" },
    { id: "bp-2", label: "Mode", value: "Spotlight Active" },
    { id: "bp-3", label: "Format", value: "Five Columns" },
  ],
  bountyItems: [
    {
      id: "bounty-1",
      title: "Signal Vault",
      tag: "Backend",
      year: "2025",
      eyebrow: "A-01 dossier",
      description:
        "Microservice-driven APIs with event relays, webhook choreography, and payment-safe request flows.",
      stack: ["Go Gin", "REST APIs", "Webhooks", "Payment Systems"],
      image: "/reference/5c5f131b-4abd-4c01-af78-99bfba287aab.png",
      ctaLabel: "View Project",
      href: "#featured",
      isFeatured: false,
    },
    {
      id: "bounty-2",
      title: "Ghost Access",
      tag: "Backend",
      year: "2026",
      eyebrow: "A-02 dossier",
      description:
        "JWT, OAuth, and layered RBAC systems designed for protected sessions and durable admin control.",
      stack: ["JWT", "OAuth", "RBAC", "Security"],
      image: "/reference/680505ce-b510-4665-8742-6ad414d00660.png",
      ctaLabel: "View Project",
      href: "#work",
      isFeatured: false,
    },
    {
      id: "bounty-3",
      title: "Neon Atlas",
      tag: "Frontend",
      year: "2025",
      eyebrow: "Prime target",
      description:
        "Live operational dashboards with cinematic data views, fast rendering, and dense monitoring surfaces.",
      stack: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
      image: "/reference/82c7d72c-4fb1-4577-8a27-f3189ac2aead.png",
      ctaLabel: "View Project",
      href: "#process",
      isFeatured: true,
    },
    {
      id: "bounty-4",
      title: "Dockline",
      tag: "DevOps",
      year: "2026",
      eyebrow: "A-03 dossier",
      description:
        "Container-first release pipelines, AWS-ready runtime setup, and deploy flows tuned for low friction.",
      stack: ["PostgreSQL", "Docker", "AWS", "Cloud Infrastructure"],
      image: "/reference/bc807e32-932f-4f06-b888-1474a2c8a0e5.png",
      ctaLabel: "View Project",
      href: "#about",
      isFeatured: false,
    },
    {
      id: "bounty-5",
      title: "Velocity Run",
      tag: "Full-Stack",
      year: "2025",
      eyebrow: "A-04 dossier",
      description:
        "Production systems shaped around latency wins, route hydration discipline, and smoother user journeys.",
      stack: ["Next.js", "Caching", "SSR", "Optimization"],
      image: "/reference/dragon-bodies.png",
      ctaLabel: "View Project",
      href: "#featured",
      isFeatured: false,
    },
  ],
  footerLinks: [
    { label: "GitHub", href: "https://github.com/michaelflorentio" },
    { label: "LinkedIn", href: "https://linkedin.com/in/michael-florentio" },
    { label: "Email", href: "mailto:maikelflorentio@gmail.com" },
  ],
};
